config {
  type: "view",
  schema: "dataform_reporting",
  name: "location_activity",
  description: "Aggregated view to track total distance and revenue by location.",
  columns: {
    location_key: "The key for the location.",
    total_distance: "The total distance of trips for the location.",
    total_revenue: "The total revenue of trips for the location."
  }
}

SELECT
  l.location_key,
  SUM(f.trip_distance) AS total_distance,
  SUM(f.total_amount) AS total_revenue
FROM
  ${ref("fact_trips")} AS f
  JOIN ${ref("dim_location")} AS l
    ON f.pickup_location_key = l.location_key
GROUP BY
  1