config {
  type: "table",
  schema: "dataform_marts",
  name: "dim_date",
  description: "Dimension table for dates.",
  columns: {
    date: "The date.",
    year: "The year of the date.",
    month: "The month of the date.",
    day: "The day of the date.",
    quarter: "The quarter of the date.",
    day_of_week: "The day of the week.",
    day_of_year: "The day of the year.",
    weekday_or_weekend: "Indicates whether the date is a weekday or weekend."
  }
}

SELECT
  date,
  EXTRACT(YEAR FROM date) AS year,
  EXTRACT(MONTH FROM date) AS month,
  EXTRACT(DAY FROM date) AS day,
  EXTRACT(QUARTER FROM date) AS quarter,
  EXTRACT(DAYOFWEEK FROM date) AS day_of_week,
  EXTRACT(DAYOFYEAR FROM date) AS day_of_year,
  CASE
    WHEN EXTRACT(DAYOFWEEK FROM date) IN (1, 7)
    THEN 'Weekend'
    ELSE 'Weekday'
  END AS weekday_or_weekend
FROM (
  SELECT
    DISTINCT pickup_date AS date
  FROM
    ${ref("stg_green_taxi_trips")}
  UNION DISTINCT
  SELECT
    DISTINCT dropoff_date AS date
  FROM
    ${ref("stg_green_taxi_trips")}
)
WHERE
  date IS NOT NULL